### ISSUE TITLE
how well should it scale?

### ISSUE THREAD

**Issue by lonnietc** [winternet/chord#1]
Hello,

I am experimenting with DHT's and P2P systems now and need something that has the potential to massively scale on the P2P side and was wondering what your estimates might be for your chord filesystem application?

Thanks

**Comment by winternet** [comment]
Hi, first off: the software is highly experimental and likely contains race conditions. 
The size of a chord ring is limited by the number of bits used for its hashes. At larger scale you should rather consider the stability of the peers: In case the ring suffers many spontaneously disconnects the operations to stabilize/fix the ring structure might have noticeable impact on the overall performance. 
You might find papers online evaluating the theoretical performance and efficiency of chord. 
Concerning this project I have not conducted any measurements regarding scalability of peers and/or performance in terms of download/upload speed but feel free to contribute.
In case you are only interested in the chord substructure you could easily plug-in you own application on top and wire your application implementing callbacks for the events emitted by chord (e.g. re-balance keys on join/leave events) and perform  measurements with your own application logic.

**Comment by lonnietc** [comment]
Will look into it more. Thanks again.
