### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by lonnietc** [winternet/chord#2]
Is there a Windows version as well?

**Comment by winternet** [comment]
No. However, you can try building the project from source. The used libraries ([conanfile.txt](https://github.com/winternet/chord/blob/main/conanfile.txt)) should be platform independent. Regarding the build process I would refer you directly to the [INSTALL.md](https://github.com/winternet/chord/blob/main/INSTALL.md) as well as the [cirecleci configuration](https://github.com/winternet/chord/blob/main/.circleci/config.yml). You will need conan and cmake to build the sources.

**Comment by lonnietc** [comment]
Thanks for the information on this
